name: example
description: Demonstrates how to use the fl_shared_link plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_shared_link:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true