name: fl_shared_link
description: Gets parameters when the app is opened, and listens to be opened
version: 0.0.3
repository: https://github.com/Wayaer/fl_shared_link.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: fl.shared.link
        pluginClass: FlSharedLinkPlugin
      ios:
        pluginClass: FlSharedLinkPlugin